[package]
name = "omini-config"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
dirs.workspace = true
indexmap.workspace = true
omini-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
uuid.workspace = true
url.workspace = true
