[package]
name = "omini-tui"
version.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
crossterm.workspace = true
dirs.workspace = true
futures-util.workspace = true
omini-domain.workspace = true
omini-protocol.workspace = true
pulldown-cmark.workspace = true
rand.workspace = true
ratatui.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
toml.workspace = true
unicode-width.workspace = true

[dev-dependencies]
uuid.workspace = true
