[package]
name = "omini-server"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
chrono.workspace = true
daemonize.workspace = true
dirs.workspace = true
futures-util.workspace = true
omini-core.workspace = true
omini-domain.workspace = true
omini-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
