[package]
name = "omini-server"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
bytes.workspace = true
chrono.workspace = true
daemonize.workspace = true
dirs.workspace = true
futures-util.workspace = true
omini-config.workspace = true
omini-core.workspace = true
omini-domain.workspace = true
omini-protocol.workspace = true
omini-runtime-contract.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio-tungstenite.workspace = true
